steps:
- name: 'gcr.io/cloud-builders/docker'
  env:
  - 'DOCKER_BUILDKIT=1'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/kazukgw-prvt/devenv'
  - 'base_image'
images: ['gcr.io/kazukgw-prvt/devenv']
timeout: 3000s
