steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  env:
  - 'DOCKER_BUILDKIT=1'
  args:
  - --destination=gcr.io/kazukgw-prvt/devenv
  - --dockerfile=base_image/Dockerfile
  - --cache=true
  - --cache-ttl=10h
timeout: 3600s
