steps:
- name: 'gcr.io/cloud-builders/docker:latest'
  env:
  - 'DOCKER_BUILDKIT=1'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/kazukgw-prvt/devenv'
  - 'base_image'
timeout: 7200s
images: ['gcr.io/kazukgw-prvt/devenv']
