format = """
[](#FC5D7C)\
$username\
[](bg:#FC5D7C fg:#FC5D7C)\
$directory\
[](fg:#FC5D7C bg:#F39660)\
$git_branch\
$git_status\
[](fg:#F39660 bg:#8cb865)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#8cb865 bg:#77bdd9)\
$time\
[ ](fg:#77bdd9)\
"""


# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
# style_user = "bg:#9A348E"
# style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
# style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#FF6077"
format = "[ $path ]($style)"
truncation_length = 8
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#F39660"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#F39660"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[ocaml]
symbol = "🐫 "
style = "bg:#8cb865"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#77bdd9"
format = '[ $time ]($style)'
