steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/kazukgw-prvt/devenv-sample'
  - '--build-arg'
  - 'USER=developer'
  - '--build-arg'
  - 'USERID=501'
  - '--build-arg'
  - 'DOCKER_GID=999'
  - '--build-arg'
  - 'PASSWORD=password'
  - '--build-arg'
  - 'HOMEDIR=/Users/developer/devenv'
  - 'setup_tools'
images: ['gcr.io/kazukgw-prvt/devenv-sample']
timeout: 1800s
